name: cryoet
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - natsort
  - tqdm

  - snakemake
  - kaggle
  - ipykernel
  - notebooks
  
  - numpy
  - pandas
  - einops
  - scikit-learn
  - umap-learn
  
  - dask
  - zarr

  - matplotlib
  - seaborn
  
  - ipytree
  - pytorch
  - torchvision
  - fastai
  - monai
  - timm
  
  - gputil
  - pip:
    - imbalanced-learn
    - copick[all]
    - napari[all]
    - pytorchvideo
    - tensorboard
variables:
  DATA_DIR: /path/to/cryoet/data
  SRC_DIR: /path/to/kaggle/cryoet/src
  REPO_DIR: /path/to/kaggle/cryoet
  TRIPATH_DIR: /path/to/deep-learning-models/TriPath
